from datetime import datetime, timezone
from app.utils.logger import get_logger

logger = get_logger(__name__)


def build_report(prediction: dict, mask_metrics: dict, session_id: str) -> str:
    """
    Build a structured full radiology report in plain text.
    Follows the standard SOAP-style radiology report format:
        - Examination
        - Clinical Indication
        - Technique
        - Findings
        - Impression

    This text is stored in the 'report' column and is the document
    the reviewing physician reads.
    """
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    disease_label = prediction.get("disease_label", "undetermined")
    confidence = prediction.get("confidence", 0.0)
    reasoning = prediction.get("reasoning", "No additional reasoning provided.")
    model_used = prediction.get("model_used", "unknown")

    # --- FINDINGS section ---
    findings_lines = []

    organ_findings = [f for f in mask_metrics.get("findings", []) if not f["is_lesion"]]
    lesion_findings = mask_metrics.get("lesion_findings", [])

    if organ_findings:
        findings_lines.append("ORGANS:")
        for f in organ_findings:
            findings_lines.append(
                f"  - {f['structure_class'].replace('_', ' ').title()}: "
                f"{f['volume_cm3']:.1f} cm³"
            )

    if lesion_findings:
        findings_lines.append("")
        findings_lines.append("LESIONS:")
        for f in lesion_findings:
            name = f["structure_class"].replace("_", " ").title()
            loc = f["location_voxel"]
            findings_lines.append(
                f"  - {name}: size {f['size_mm']:.1f}mm, "
                f"volume {f['volume_cm3']:.2f} cm³, "
                f"{f['num_instances']} instance(s), "
                f"centroid voxel {loc}"
            )
    else:
        findings_lines.append("LESIONS: None detected.")

    findings_text = "\n".join(findings_lines)

    report = f"""CT DISEASE ANALYSIS REPORT
==========================
Session ID : {session_id}
Generated  : {now}
AI Model   : {model_used.upper()}

EXAMINATION
-----------
CT scan (3D volumetric, DICOM input)

TECHNIQUE
---------
Automated segmentation performed using NVIDIA VISTA-3D (127-class model).
Disease prediction performed using {model_used.upper()}.

FINDINGS
--------
{findings_text}

IMPRESSION
----------
Primary diagnosis : {disease_label}
Confidence        : {confidence * 100:.1f}%
Reasoning         : {reasoning}

NOTES
-----
This report was generated by an AI pipeline and is intended to assist,
not replace, clinical judgment. Findings with confidence below threshold
or critical lesions are flagged for mandatory physician review.
"""

    logger.info("report_built", session_id=session_id, length=len(report))
    return report
